song_list = ["Bruno Major - Easily (2017)",
             "퍼센트 PERC%NT - Weekend (2017)",
             "Snoh Aalegra - Fool For You (2017)",
             "Pink Sweat$ - Honesty (2018)",
             "Mac Ayres - Slow Down (2017)",
             "H.E.R. - Focus (2016)",
             "Daniel Caesar - Best Part (feat. H.E.R.) (2017)",
             "José James - To Be With You (2017)",
             "Tyler, The Creator - See You Again (feat. Kali Uchis) [Slowed + Reverb] (onesung edit) (2017)",
             "Kali Uchis - After The Storm (feat. Tyler, The Creator & Booty Colins) (2018)",
             "Gallant - Weight In Gold (2016)",
             "FKJ - Is Magic Gone (2018)",
             "Childish Gambino - Sober (2014)",
             "KATIE - Thinkin Bout You (2019)",
             "jeebanoff (지바노프) - We (OUI) (ft. sogumm) [Slowed + Reverb] (onesung edit) (2019)",
             "Joji - SLOW DANCING IN THE DARK (2018)",
             "DRESS & Lydia Paek - EMOTION (2015)",
             "Lauv - Paris In The Rain (HYE SUNG Cover) (2018)",
             "Jeff Bernat - If You Wonder (2012)",
             "McKay & Jeff Bernat - Angel 2 Me (2015)"]  # Sample Songs
